# Generated by Django 5.1.7 on 2026-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(default='Module 2: Practical', max_length=100)),
                ('study_content', models.TextField()),
            ],
        ),
    ]
