# Generated by Django 5.1.7 on 2026-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_rename_name_task_title_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='General', max_length=25),
        ),
    ]
