# Generated by Django 5.1.7 on 2026-01-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0005_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Intren',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
