# Generated by Django 5.1.7 on 2026-01-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_remove_profile_enrollment_date_alter_profile_intren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Intren',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('SQL', 'SQL'), ('Power BI', 'Power BI'), ('Python', 'Python'), ('Django', 'Django')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='period',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('SQL', 'SQL'), ('Power BI', 'Power BI'), ('Python', 'Python'), ('Django', 'Django')], max_length=50),
        ),
    ]
