# Generated by Django 5.1.7 on 2026-01-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_alter_profile_intren_alter_profile_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
