# Generated by Django 5.1.7 on 2026-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_task_description_task_due_date_task_task_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_period',
            field=models.IntegerField(default=1, help_text='1 for 1 Month, 2 for 2 Months, etc.'),
        ),
    ]
