# Generated by Django 5.1.7 on 2026-02-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0011_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('week_number', models.IntegerField(default=1, help_text='Week number (1, 2, 3...)')),
                ('order', models.IntegerField(default=1, help_text='Order within the week')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vision.task')),
            ],
            options={
                'ordering': ['week_number', 'order'],
            },
        ),
    ]
