# Generated by Django 5.1.7 on 2026-02-09 17:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0012_learningmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
