# Generated by Django 5.1.7 on 2026-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('domain', models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI', 'Power BI'), ('Machine Learning', 'Machine Learning'), ('Web Development', 'Web Development'), ('Cloud Computing', 'Cloud Computing'), ('Other', 'Other')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='UPI Transaction ID', max_length=100, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
