# Generated by Django 5.1.7 on 2026-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0015_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('BI Dashboards', 'BI Dashboards'), ('Predictive AI', 'Predictive AI'), ('Cloud Data', 'Cloud Data'), ('Other', 'Other')], default='Other', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
