# Generated by Django 5.1.7 on 2026-02-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0016_clientrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem_statement', models.FileField(help_text='Upload PDF/Doc of the problem statement', upload_to='projects/')),
                ('category', models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('SQL', 'SQL'), ('Power BI', 'Power BI'), ('Python', 'Python'), ('Django', 'Django')], max_length=50)),
                ('required_period', models.IntegerField(default=1, help_text='Minimum internship duration required (in months)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
