# Generated by Django 5.1.7 on 2026-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0017_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('min_period', models.IntegerField(choices=[(1, '1 Month Interns (and above)'), (2, '2 Months Interns (and above)'), (3, '3 Months Interns (and above)'), (6, '6 Months Interns only')], default=1, help_text='Show this notice to interns whose period is >= this value')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project1Month',
            fields=[
            ],
            options={
                'verbose_name': 'Project – 1 Month',
                'verbose_name_plural': '📗 Projects – 1 Month',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.project',),
        ),
        migrations.CreateModel(
            name='Project2Months',
            fields=[
            ],
            options={
                'verbose_name': 'Project – 2 Months',
                'verbose_name_plural': '📘 Projects – 2 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.project',),
        ),
        migrations.CreateModel(
            name='Project3Months',
            fields=[
            ],
            options={
                'verbose_name': 'Project – 3 Months',
                'verbose_name_plural': '📙 Projects – 3 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.project',),
        ),
        migrations.CreateModel(
            name='Project6Months',
            fields=[
            ],
            options={
                'verbose_name': 'Project – 6 Months',
                'verbose_name_plural': '📕 Projects – 6 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.project',),
        ),
        migrations.CreateModel(
            name='Task1Month',
            fields=[
            ],
            options={
                'verbose_name': 'Task – 1 Month',
                'verbose_name_plural': '📗 Tasks – 1 Month',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.task',),
        ),
        migrations.CreateModel(
            name='Task2Months',
            fields=[
            ],
            options={
                'verbose_name': 'Task – 2 Months',
                'verbose_name_plural': '📘 Tasks – 2 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.task',),
        ),
        migrations.CreateModel(
            name='Task3Months',
            fields=[
            ],
            options={
                'verbose_name': 'Task – 3 Months',
                'verbose_name_plural': '📙 Tasks – 3 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.task',),
        ),
        migrations.CreateModel(
            name='Task6Months',
            fields=[
            ],
            options={
                'verbose_name': 'Task – 6 Months',
                'verbose_name_plural': '📕 Tasks – 6 Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vision.task',),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_period',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months')], default=1, help_text='Which intern period this project belongs to'),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_period',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months')], default=1, help_text='Which intern period this task belongs to'),
        ),
    ]
