# Generated by Django 5.2.9 on 2026-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0018_announcement_project1month_project2months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UPI/Razorpay Transaction ID', max_length=100, null=True),
        ),
    ]
