# Generated by Django 5.1.7 on 2026-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0019_enrollment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='domain',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Webdevlopment', 'Webdevlopment'), ('ML', 'ML'), ('data science', 'data science'), ('aI', 'aI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Intren',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Webdevlopment', 'Webdevlopment'), ('ML', 'ML'), ('data science', 'data science'), ('aI', 'aI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Webdevlopment', 'Webdevlopment'), ('ML', 'ML'), ('data science', 'data science'), ('aI', 'aI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Webdevlopment', 'Webdevlopment'), ('ML', 'ML'), ('data science', 'data science'), ('aI', 'aI')], max_length=50),
        ),
    ]
