# Generated by Django 5.1.7 on 2026-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0020_alter_enrollment_domain_alter_profile_intren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='service_type',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('Power BI ', 'Power BI'), ('Predictive AI', 'Predictive AI'), ('Cloud Data', 'Cloud Data'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='domain',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Intren',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Web development', 'Web development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=50),
        ),
    ]
