# Generated by Django 5.1.7 on 2026-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0022_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Amount in INR (e.g. 199.00)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Show this duration option on the enrollment page')),
            ],
            options={
                'verbose_name': 'Internship Pricing',
                'verbose_name_plural': 'Internship Pricing',
                'ordering': ['duration'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=50),
        ),
    ]
