# Generated by Django 5.1.7 on 2026-03-15 16:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0023_internshippricing_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
