# Generated by Django 5.2.12 on 2026-04-14 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0026_userstreak_dailycheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='submitted_answer',
            field=models.TextField(blank=True, help_text="Student's submitted answer / approach / GitHub link", null=True),
        ),
        migrations.CreateModel(
            name='DailyChallengeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this challenge is active')),
                ('category', models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Power BI developer', 'Power BI developer'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('description', models.TextField(help_text='Full problem statement shown to the student')),
                ('hint', models.TextField(blank=True, help_text='Optional hint shown on demand', null=True)),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'ordering': ['-date'],
                'unique_together': {('date', 'category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='vision.dailychallengetask'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together={('user', 'challenge')},
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='activity_description',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='domain',
        ),
    ]
