# Generated by Django 5.2.12 on 2026-04-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0027_rename_created_at_dailycheckin_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailychallengetask',
            options={'verbose_name': 'Legacy Daily Challenge'},
        ),
        migrations.AlterModelOptions(
            name='dailycheckin',
            options={'verbose_name': 'Legacy Daily Check-In'},
        ),
        migrations.AlterUniqueTogether(
            name='dailychallengetask',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailychallengetask',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dailychallengetask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailychallengetask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailychallengetask',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailychallengetask',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.dailychallengetask'),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='submitted_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChallengeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='⚡', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='System tracks are shown to all users as optional presets.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Track',
                'verbose_name_plural': 'Challenge Tracks',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrackCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, help_text='Optional: what did you do?', max_length=300)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='vision.challengetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Track Check-In',
                'verbose_name_plural': 'Daily Track Check-Ins',
                'ordering': ['-date'],
                'unique_together': {('user', 'track', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_days', models.IntegerField(choices=[(30, '30 Days'), (50, '50 Days'), (100, '100 Days'), (200, '200 Days'), (300, '300 Days'), (500, '500 Days — Legend 🎁')])),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('reward_sent', models.BooleanField(default=False, help_text='Mark true when ₹500 gift card is sent (500-day only)')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='vision.challengetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Achievement',
                'verbose_name_plural': 'Milestone Achievements',
                'unique_together': {('user', 'track', 'milestone_days')},
            },
        ),
        migrations.CreateModel(
            name='UserChallengeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_days', models.IntegerField(choices=[(30, '30 Days  — Starter'), (50, '50 Days  — Committed'), (100, '100 Days — Dedicated'), (200, '200 Days — Elite'), (300, '300 Days — Master'), (500, '500 Days — Legend  🎁 ₹500 Gift Card')], default=30)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='vision.challengetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Challenge Enrollment',
                'verbose_name_plural': 'User Challenge Enrollments',
                'unique_together': {('user', 'track')},
            },
        ),
    ]
