# Generated by Django 5.2.12 on 2026-05-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0028_alter_dailychallengetask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('Power BI', 'Power BI'), ('Predictive AI', 'Predictive AI'), ('Cloud Data', 'Cloud Data'), ('Other', 'Other')], default='Other', max_length=100)),
                ('status', models.CharField(choices=[('discovery', 'Discovery'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='discovery', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Overall progress 0–100%')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total project budget in INR', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='vision.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Project',
                'verbose_name_plural': 'Client Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vision.clientproject')),
            ],
            options={
                'verbose_name': 'Client Invoice',
                'verbose_name_plural': 'Client Invoices',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='client_deliverables/')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='vision.clientproject')),
            ],
            options={
                'verbose_name': 'Project Deliverable',
                'verbose_name_plural': 'Project Deliverables',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='vision.clientproject')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='vision.clientproject')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
