# Generated by Django 5.2.12 on 2026-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0029_clientprofile_clientproject_clientinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='credentials_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='generated_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
