# Generated by Django 5.2.12 on 2026-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0030_enrollment_approved_at_enrollment_credentials_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='offer_letter_sent',
            field=models.BooleanField(default=False, help_text='Set to True after offer letter has been emailed to the student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, help_text='Admin-set internship start date (used on offer letter & certificate)', null=True),
        ),
    ]
