# Generated by Django 5.2.12 on 2026-08-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0034_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reviewer full name', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Title / Company (e.g. Intern - Data Science)', max_length=150)),
                ('message', models.TextField(help_text='Review / testimonial text')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_approved', models.BooleanField(default=False, help_text='Tick to show this review on the public homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='progress',
            field=models.IntegerField(default=0, help_text='Overall progress 0-100%'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Email body text. See the placeholder reference for available variables.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter Email'), ('login_credentials', 'Login Credentials Email')], help_text='Internal identifier. Do not change.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='milestoneachievement',
            name='milestone_days',
            field=models.IntegerField(choices=[(30, '30 Days'), (50, '50 Days'), (100, '100 Days'), (200, '200 Days'), (300, '300 Days'), (500, '500 Days - Legend')]),
        ),
        migrations.AlterField(
            model_name='milestoneachievement',
            name='reward_sent',
            field=models.BooleanField(default=False, help_text='Mark true when Rs.500 gift card is sent (500-day only)'),
        ),
        migrations.AlterField(
            model_name='userchallengeenrollment',
            name='target_days',
            field=models.IntegerField(choices=[(30, '30 Days  - Starter'), (50, '50 Days  - Committed'), (100, '100 Days - Dedicated'), (200, '200 Days - Elite'), (300, '300 Days - Master'), (500, '500 Days - Legend  Rs.500 Gift Card')], default=30),
        ),
    ]
